import { environment } from "src/environments/environment";

export var url = {
    urlHit: environment.production ? 'https://medsmanual.com/wp-json/api/' : 'https://medsmanual.com/wp-json/api/',
    urlMidtrans: environment.production ? 'https://api.midtrans.com/' : 'https://app.sandbox.midtrans.com/',
}

export var dataTemp = {
    route: {
        'detail': '/tabs/detail',
        'asesmen': '/tabs/asesmen',
        'triase': '/tabs/asesmen/triase',
        'surveiPrimer': '/tabs/asesmen/survei-primer',
        'surveiSekunder': '/tabs/asesmen/survei-sekunder',
        'tandaVital': '/tabs/asesmen/tanda-vital',
        'asesmenDetail': '/tabs/asesmen/asesmen-detail',
        'penunjang': '/tabs/penunjang',
        'radioimaging': '/tabs/penunjang/radioimaging',
        'nilaiNormalLab': '/tabs/penunjang/nilai-normal-lab',
        'ekg': '/tabs/penunjang/ekg',
        'penunjangDetail': '/tabs/penunjang/penunjang-detail',
        'panduan': '/tabs/panduan',
        'panduanDetail': '/tabs/panduan/panduan-detail',
        'obat': '/tabs/obat',
        'content': '/tabs/content',
        'contentTwo': '/tabs/content-two',
        'contentThree': '/tabs/content-three',
        'contentFour': '/tabs/content-four',
        'contentFive': '/tabs/content-five',
        'contentSix': '/tabs/content-six',
        'contentAsesmen': '/tabs/asesmen/content',
        'contentAsesmenTwo': '/tabs/asesmen/content-two',
        'contentAsesmenThree': '/tabs/asesmen/content-three',
        'contentAsesmenFour': '/tabs/asesmen/content-four',
        'contentAsesmenFive': '/tabs/asesmen/content-five',
        'contentAsesmenSix': '/tabs/asesmen/content-six',
        'contentPenunjang': '/tabs/penunjang/content',
        'contentPenunjangTwo': '/tabs/penunjang/content-two',
        'contentPenunjangThree': '/tabs/penunjang/content-three',
        'contentPenunjangFour': '/tabs/penunjang/content-four',
        'contentPenunjangFive': '/tabs/penunjang/content-five',
        'contentPenunjangSix': '/tabs/penunjang/content-six',
        'contentPanduan': '/tabs/panduan/content',
        'contentPanduanTwo': '/tabs/panduan/content-two',
        'contentPanduanThree': '/tabs/panduan/content-three',
        'contentPanduanFour': '/tabs/panduan/content-four',
        'contentPanduanFive': '/tabs/panduan/content-five',
        'contentPanduanSix': '/tabs/panduan/content-six',
        'contentObat': '/tabs/obat/content',
        'contentObatTwo': '/tabs/obat/content-two',
        'contentObatThree': '/tabs/obat/content-three',
        'contentObatFour': '/tabs/obat/content-four',
        'contentObatFive': '/tabs/obat/content-five',
        'contentObatSix': '/tabs/obat/content-six',
        'searchContent': '/search-content',
        'searchContentTwo': '/search-content-two',
        'searchContentThree': '/search-content-three',
        'searchContentFour': '/search-content-four',
        'searchContentFive': '/search-content-five',
        'searchContentSix': '/search-content-six',
        'admin': '/tabs/profil/admin',
        'master': '/tabs/profil/admin/master',
        'masterTwo': '/tabs/profil/admin/master-two',
        'masterThree': '/tabs/profil/admin/master-three',
        'masterFour': '/tabs/profil/admin/master-four',
        'masterFive': '/tabs/profil/admin/master-five',
        'masterSix': '/tabs/profil/admin/master-six',
        'createEditMaster': '/tabs/profil/admin/master/create-edit-master',
        'createEditMasterTwo': '/tabs/profil/admin/master-two/create-edit-master-two',
        'createEditMasterThree': '/tabs/profil/admin/master-three/create-edit-master-three',
        'createEditMasterFour': '/tabs/profil/admin/master-four/create-edit-master-four',
        'createEditMasterFive': '/tabs/profil/admin/master-five/create-edit-master-five',
        'createEditMasterSix': '/tabs/profil/admin/master-six/create-edit-master-six',
        'users': '/tabs/profil/admin/users',
    },
    url: {
        'login': url.urlHit + 'login',
        'getUsers': url.urlHit + 'getUsers',
        'getContents': url.urlHit + 'getContents',
        'getContentsbyId': url.urlHit + 'getContentsbyId',
        'getContentsbyName': url.urlHit + 'getContentsbyName',
        'getContentbyData': url.urlHit + 'getContentbyData',
        'searchContentsbyData': url.urlHit + 'searchContentsbyData',
        'createContent': url.urlHit + 'createContent',
        'updateContent': url.urlHit + 'updateContent',
        'getFireUserSummary': url.urlHit + 'getFireUserSummary',
        'getFireUsers': url.urlHit + 'getFireUsers',
        'getFireUsersLimit': url.urlHit + 'getFireUsersLimit',
        'searchFireUsersLimit': url.urlHit + 'searchFireUsersLimit',
        'getFireUsersbyId': url.urlHit + 'getFireUsersbyId',
        'getFireUsersbyEmail': url.urlHit + 'getFireUsersbyEmail',
        'getFireUsersLogin': url.urlHit + 'getFireUsersLogin',
        'createFireUser': url.urlHit + 'createFireUser',
        'updateFireUser': url.urlHit + 'updateFireUser',
        'checkIsMember': url.urlHit + 'checkIsMember/',
        'charge': url.urlHit + 'midtrans/charge',
        'charge2': url.urlHit + 'midtrans/charge2',
        'status': url.urlHit + 'midtrans/status/',
        'getTransactions': url.urlHit + 'getTransactions',
        'getTransactionbyId': url.urlHit + 'getTransactionbyId',
        'createTransaction': url.urlHit + 'createTransaction',
        'updateTransaction': url.urlHit + 'updateTransaction',
        'getSubscriptions': url.urlHit + 'getSubscriptions',
        'getSubscriptionbyId': url.urlHit + 'getSubscriptionbyId',
        'createSubscription': url.urlHit + 'createSubscription',
        'updateSubscription': url.urlHit + 'updateSubscription',
    },
    urlMidtrans: {
        'snapTransactions': url.urlMidtrans + 'snap/v1/transactions',
        'charge': url.urlMidtrans + 'v2/charge'
    },
    tab: {
        'asesmen': 'asesmen',
        'triase': 'triase',
        'triaseChild': 'triase-child',
        'surveiPrimer': 'survei-primer',
        'surveiSekunder': 'survei-sekunder',
        'tandaVital': 'tanda-vital',
        'penunjang': 'penunjang',
        'radioimaging': 'radioimaging',
        'nilaiNormalLab': 'nilai-normal-lab',
        'ekg': 'ekg',
        'panduan': 'panduan',
        'panduanKasus': 'panduan-kasus',
        'panduanTindakan': 'panduan-tindakan',
        'pengukuran': 'pengukuran',
        'obat': 'obat',
        'profil': 'profil',
        'admin': 'admin',
        'master': 'master',
        'createEditMaster': 'create-edit-master',
    },
    title: {
        'triase': 'Triase',
        'surveiPrimer': 'Survei Primer',
        'surveiSekunder': 'Survei Sekunder',
        'tandaVital': 'Tanda Vital',
        'radioimaging': 'Radioimaging',
        'nilaiNormalLab': 'Laboratorium',
        'ekg': 'Elektrokardiografi',
        'panduanKasus': 'Panduan Kasus',
        'panduanTindakan': 'Panduan Tindakan',
        'pengukuran': 'Pengukuran',
        'obat': 'Daftar Obat',
    },
    aksi: {
        'create': 'create',
        'edit': 'edit',
    },
    icon: {
        'urlIconAsesmen': '/assets/icons/asesmen.svg',
        'urlIconAsesmenSelected': '/assets/icons/asesmen-selected.svg',
        'urlIconPenunjang': '/assets/icons/penunjang.svg',
        'urlIconPenunjangSelected': '/assets/icons/penunjang-selected.svg',
        'urlIconPanduan': '/assets/icons/panduan.svg',
        'urlIconPanduanSelected': '/assets/icons/panduan-selected.svg',
        'urlIconObat': '/assets/icons/obat.svg',
        'urlIconObatSelected': '/assets/icons/obat-selected.svg',
        'urlIconProfil': '/assets/icons/profil.svg',
        'urlIconProfilSelected': '/assets/icons/profil-selected.svg',
    },
    log: {
        'login': 'login',
        'logout': 'logout',
        'register': 'register',
        'subscibe': 'subscibe',
        'browse': 'browse',
        'search': 'search',
        'editMaster': 'edit-master',
        'fetch': 'fetch',
        'updateProfile': 'update-profile',
        'createTransaction': 'create-transaction',
        'charge': 'charge',
    },
    logMessage: {
        'success': 'Berhasil',
        'failed': 'Gagal',
        'login': 'login',
        'logout': 'logout',
        'register': 'register',
        'subscibe': 'subscibe',
        'browse': 'browse',
        'search': 'search',
        'editMaster': 'edit-master',
        'fetch': 'fetch',
        'updateProfile': 'update-profile',
        'createTransaction': 'create-transaction',
        'chargeSuccess': 'Berhasil melakukan Charge Tr',
    },
    typeOld: {
        'text': 'text',
        'sub': 'sub',
        'subsub': 'subsub',
        'img': 'img',
        'ref': 'ref',
        'btn': 'btn',
        'audio': 'audio',
    },
    type: {
        'text': 'Teks',
        'textWithMargin': 'Teks Dengan Margin',
        'textWithoutMargin': 'Teks Tanpa Margin',
        'sub': 'Sub Judul',
        'subWithoutMargin': 'Sub Judul Tanpa Margin',
        'subsub': 'Sub Sub Judul',
        'subsubWithoutMargin': 'Sub Sub Judul Tanpa Margin',
        'img': 'Image',
        'ref': 'Referensi',
        'btn': 'Button',
        'btnOutline': 'Button Outline',
        'audio': 'Audio',
        'teksCenter': 'Teks Center',
        'teksCenterWithoutMargin': 'Teks Center Tanpa Margin',
        'numbering0': 'Numbering 0',
        'numbering1': 'Numbering 1',
        'numbering2': 'Numbering 2',
        'numbering3': 'Numbering 3',
        'numbering4': 'Numbering 4',
        'numbering5': 'Numbering 5',
        'numbering6': 'Numbering 6',
        'numbering0WithoutMargin': 'Numbering 0 Tanpa Margin',
        'numbering1WithoutMargin': 'Numbering 1 Tanpa Margin',
        'numbering2WithoutMargin': 'Numbering 2 Tanpa Margin',
        'numbering3WithoutMargin': 'Numbering 3 Tanpa Margin',
        'numbering4WithoutMargin': 'Numbering 4 Tanpa Margin',
        'numbering5WithoutMargin': 'Numbering 5 Tanpa Margin',
        'numbering6WithoutMargin': 'Numbering 6 Tanpa Margin',
        'footer': 'Footer',
    },
    audio: {
        'auskultasiNormalVesikuler': 'auskultasi-normal-vesikuler',
        'crackles': 'crackles',
        'pleuralRub': 'pleural-rub',
        'stridor': 'stridor',
        'wheezing': 'wheezing',
        'suaraJantungNormal': 'suara-jantung-normal',
        'suaraS3': 'suara-s3',
        'suaraS4': 'suara-s4',
        'murmurBenign': 'murmur-benign',
        'lateArterialStenosis': 'late-arterial-stenosis',
        'pulmonicStenosis': 'pulmonic-stenosis',
        'mitralRegurgitation': 'mitral-regurgitation',
        'patentDuctusArteriosus': 'patent-ductus-arteriosus',
        'ventricularSeptalDefect': 'ventricular-septal-defect',
        'atrialSeptalDefect': 'atrial-septal-defect',
        'aorticRegurgitation': 'aortic-regurgitation',
        'mitralStenosis': 'mitral-stenosis',
    },
    bagian: {
        'asesmen': 'Asesmen',
        'penunjang': 'Penunjang',
        'panduan': 'Panduan',
        'obat': 'Obat',
    },
    status: {
        active: 'active',
        inactive: 'inactive'
    },
    master: {
        photo: 'https://ionicframework.com/docs/img/demos/avatar.svg'
    },
    keyStrg: {
        profile: 'profile',
        transaction_id: 'transaction_id',
    },
    responsActions: {
        generateqrcode: 'generate-qr-code',
        deeplinkredirect: 'deeplink-redirect',
        getstatus: 'get-status',
        cancel: 'cancel'
    },
    payment_type: {
        gopay: 'gopay'
    },
    transaction_status: {
        authorize: 'authorize',
        capture: 'capture',
        settlement: 'settlement',
        deny: 'deny',
        pending: 'pending',
        cancel: 'cancel',
        refund: 'refund',
        partial_refund: 'partial_refund',
        chargeback: 'chargeback',
        partial_chargeback: 'partial_chargeback',
        expire: 'expire',
        failure: 'failure'
    }
}