import { environment } from "src/environments/environment";
export var dataTemp = {
    // urlHit: environment.production ? 'https://kip.hutamakarya.com/api/' :  'http://kipdev.hutamakarya.com/',
    urlHit: environment.production ? 'https://ppid.hutamakarya.com/api/' : 'https://ppiddev.hutamakarya.com/api/',
    tab: {
        'asesmen': 'asesmen',
        'triase': 'triase',
        'triaseChild': 'triase-child',
        'surveiPrimer': 'survei-primer',
        'surveiSekunder': 'survei-sekunder',
        'tandaVital': 'tanda-vital',
        'penunjang': 'penunjang',
        'panduan': 'panduan',
        'obat': 'obat',
        'profil': 'profil',
        'admin': 'admin',
        'master': 'master',
        'createEditMaster': 'create-edit-master',
    },
    title: {
        'triase': 'Triase',
        'surveiPrimer': 'Survei Primer',
        'surveiSekunder': 'Survei Sekunder',
        'tandaVital': 'Tanda Vital',
    },
    aksi: {
        'create': 'create',
        'edit': 'edit',
    },
    icon: {
        'urlIconAsesmen': '/assets/icons/asesmen.svg',
        'urlIconAsesmenSelected': '/assets/icons/asesmen-selected.svg',
        'urlIconPenunjang': '/assets/icons/penunjang.svg',
        'urlIconPenunjangSelected': '/assets/icons/penunjang-selected.svg',
        'urlIconPanduan': '/assets/icons/panduan.svg',
        'urlIconPanduanSelected': '/assets/icons/panduan-selected.svg',
        'urlIconObat': '/assets/icons/obat.svg',
        'urlIconObatSelected': '/assets/icons/obat-selected.svg',
        'urlIconProfil': '/assets/icons/profil.svg',
        'urlIconProfilSelected': '/assets/icons/profil-selected.svg',
    },
    log: {
        'login': 'login',
        'logout': 'logout',
        'register': 'register',
        'subscibe': 'subscibe',
        'browse': 'browse',
        'search': 'search',
        'editMaster': 'edit-master',
    },
    subCategory: {
        'text': 'text',
        'sub': 'sub',
        'img': 'img',
        'ref': 'ref',
    },
    subCategoryString: {
        'text': 'Teks',
        'sub': 'Sub Judul',
        'img': 'Image',
        'ref': 'Referensi',
    },
}